// Convert the approved sample-value templates into merge-field templates.
// Output: lib/emails/defaults/<key>.html  (tokens like {{model}}, {{HERO}}, {{PREHEADER}}).
import fs from "node:fs";
import path from "node:path";

const SRC = "emails/templates";
const OUT = "lib/emails/defaults";
fs.mkdirSync(OUT, { recursive: true });

const keyFor = (f) => f.replace(/^\d+-/, "").replace(/\.html$/, "");

// Global, unambiguous data -> token replacements.
const GLOBAL = [
  ['The Six', '{{model}}'],
  ['EB-2026-0001', '{{orderRef}}'],
  ['British Racing Green', '{{colour}}'],
  ['18" Machined Alloy', '{{wheels}}'],
  ['Tan Premium', '{{interior}}'],
  ['Logo on front and both sides', '{{branding}}'],
  ['£28,950.00', '{{total}}'],
  ['Electric Buggies Ltd', '{{bankName}}'],
  ['GB00 0000 0000 0000 00', '{{bankIban}}'],
  ['00-00-00', '{{bankSort}}'],
  ['00000000', '{{bankAccount}}'],
  ['September 2026', '{{estDelivery}}'],
  ['Welcome aboard, James', 'Welcome aboard, {{firstName}}'],
  ['+44 (0)20 0000 0000', '{{phone}}'],
];

// Per-file extra replacements (ambiguous values).
const PER_FILE = {
  "order-confirmed": [['The Six', '{{model}}'], ['EB-2026-0001', '{{orderRef}}']],
  "payment-details": [['EB-2026-0001', '{{paymentRef}}']],
  "payment-received": [['Production scheduled', '{{stage}}']],
  "order-update": [['Your buggy is in production', '{{stageHeadline}}'], ['In production', '{{stage}}']],
  "delivered": [['The Six', '{{model}}'], ['EB-2026-0001', '{{orderRef}}'], ['Active', '{{warrantyStatus}}']],
};

function tokenizeHero(html) {
  // The grey placeholder hero block (contains "Your vehicle") -> {{HERO}}.
  const re = /<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f5f6f7;border:1px solid #e3e5e8;border-radius:8px;">[\s\S]*?Your vehicle[\s\S]*?<\/table>/;
  return html.replace(re, "{{HERO}}");
}

function tokenizeLinks(html) {
  // Footer links by text.
  html = html.replace(/<a href="#"([^>]*)>Visit your account<\/a>/g, '<a href="{{accountLink}}"$1>Visit your account</a>');
  html = html.replace(/<a href="#"([^>]*)>Privacy<\/a>/g, '<a href="{{privacyLink}}"$1>Privacy</a>');
  html = html.replace(/<a href="#"([^>]*)>Unsubscribe<\/a>/g, '<a href="{{unsubscribeLink}}"$1>Unsubscribe</a>');
  // Primary buttons (display:inline-block ... background). First -> ctaLink, second -> ctaLink2.
  let n = 0;
  html = html.replace(/href="#"(\s*style="display:inline-block)/g, (_, s) => `href="${n++ === 0 ? "{{ctaLink}}" : "{{ctaLink2}}"}"${s}`);
  // Any remaining href="#" -> accountLink (safe default).
  html = html.replace(/href="#"/g, 'href="{{accountLink}}"');
  return html;
}

function addPreheader(html) {
  return html.replace(/(<body[^>]*>)/, `$1\n<div style="display:none;max-height:0;overflow:hidden;mso-hide:all;opacity:0;color:transparent;height:0;width:0;">{{PREHEADER}}</div>`);
}

const files = fs.readdirSync(SRC).filter((f) => f.endsWith(".html")).sort();
const bundle = {};
for (const f of files) {
  const key = keyFor(f);
  let html = fs.readFileSync(path.join(SRC, f), "utf8");
  html = tokenizeHero(html);
  for (const [a, b] of (PER_FILE[key] || [])) html = html.split(a).join(b);
  for (const [a, b] of GLOBAL) html = html.split(a).join(b);
  html = tokenizeLinks(html);
  html = addPreheader(html);
  fs.writeFileSync(path.join(OUT, key + ".html"), html);
  bundle[key] = html;
  const leftover = [...html.matchAll(/EB-2026|The Six|British Racing|£28,950|00-00-00/g)].length;
  console.log(`${key}: HERO=${html.includes("{{HERO}}")} tokens=${(html.match(/\{\{/g) || []).length} leftoverSamples=${leftover}`);
}
// Bundled TS so the defaults load at runtime without fs tracing.
const ts = `// AUTO-GENERATED by scripts/tokenize-emails.mjs from emails/templates. Do not edit by hand.\n/* eslint-disable */\nexport const DEFAULT_TEMPLATES: Record<string, string> = ${JSON.stringify(bundle, null, 0)};\n`;
fs.writeFileSync("lib/emails/defaults.ts", ts);
console.log("wrote lib/emails/defaults.ts");
