import { defineType, defineField } from "sanity";

/** Per-page SEO object — surfaced on every document (brief §7/§9). */
export const seo = defineType({
  name: "seo",
  title: "SEO",
  type: "object",
  options: { collapsible: true, collapsed: true },
  fields: [
    defineField({ name: "metaTitle", title: "Meta title", type: "string", validation: (r) => r.max(60).warning("Keep under ~60 characters") }),
    defineField({ name: "metaDescription", title: "Meta description", type: "text", rows: 2, validation: (r) => r.max(160).warning("Keep under ~160 characters") }),
    defineField({ name: "ogImage", title: "Social share image", type: "image" }),
    defineField({ name: "canonical", title: "Canonical URL override", type: "url" }),
    defineField({ name: "noindex", title: "Hide from search engines (noindex)", type: "boolean", initialValue: false }),
  ],
});

/** Vehicle specification block. */
export const spec = defineType({
  name: "spec",
  title: "Specification",
  type: "object",
  fields: [
    defineField({ name: "seats", title: "Seats", type: "string" }),
    defineField({ name: "range", title: "Range", type: "string" }),
    defineField({ name: "battery", title: "Battery", type: "string" }),
    defineField({ name: "topSpeed", title: "Top speed", type: "string" }),
    defineField({ name: "dimensions", title: "Dimensions (L×W×H)", type: "string" }),
    defineField({ name: "charge", title: "Charge time", type: "string" }),
  ],
});

/** Image with required alt text (used in galleries — brief §8). */
export const galleryImage = defineType({
  name: "galleryImage",
  title: "Image",
  type: "object",
  fields: [
    defineField({ name: "image", title: "Image", type: "image", options: { hotspot: true } }),
    defineField({ name: "alt", title: "Alt text", type: "string", validation: (r) => r.required().warning("Alt text improves SEO & accessibility") }),
    // Background-removal variant (brief §7): cut-out stored alongside original.
    defineField({ name: "cutout", title: "Background-removed variant", type: "image", readOnly: true, description: "Generated by the Remove background action." }),
  ],
});
